sudo: required
services:
  - docker
before_install:
  - docker build -t dangermouse678/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true dangermouse678/react-test npm test
after_success:
  - docker build -t dangermouse678/multi-client ./client
  - docker build -t dangermouse678/multi-nginx ./nginx
  - docker build -t dangermouse678/multi-server ./server
  - docker build -t dangermouse678/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dangermouse678/multi-client
  - docker push dangermouse678/multi-nginx
  - docker push dangermouse678/multi-server
  - docker push dangermouse678/multi-worker
deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-020216992354
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
